server:
  port: 8761
spring:
  application:
    name: eureka_server
eureka:
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/