server:
  #服务端口
  port: 8092
spring:
  application:
    #服务名称
    name: spring-config-config-client
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.BOOT: DEBUG