server:
  #服务端口
  port: 8092
spring:
  application:
    #服务名称
    name: spring-config-config-client
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      #服务注册中心
      defaulZone: http://localhost:8761/eureka/