server:
  port: 8004
spring:
  application:
    name: eureka-client-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka-server01:8761/eureka/,http://admin:admin@eureka-server02:8762/eureka/
  instance:
    prefer-ip-address: true