server:
  #服务端口
  port: 8091
spring:
  profiles:
    #配置使用subversion仓库读取配置，相关配置还有git、native（本地文件）、vault
    active: git
  application:
    #服务名称
    name: spring-config-config-server
  cloud:
    config:
      server:
        #检查健康状况 label name profiles 分别对应分支 配置名
        health:
          repositories:
            a-foo:
              label: dev1
              name: application
              profiles: dev
        #配置git仓库地址和账户
        git:
          uri: https://github.com/90706827/spring-cloud-config.git
          #配置文件所在的分支
          default-label: dev1
          #git仓库的用户名
          username: 90706827
          #git仓库的密码 公开仓库可以不用配置
          password:
          search-paths: /**
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      #服务注册中心
      defaulZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123