server:
  port: 8001
spring:
  application:
    name: eureka-client
eureka:
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    appname: eureka-client
  client:
    healthcheck:
      #开启健康检查 自定义MyHealthHealthCheckHandler在定时向eureka server发送心跳
      enabled: true
    serviceUrl:
      #将服务注册到eureka server上，高可用配置两个eureka server
      #C:\Windows\System32\drivers\etc\hosts 设置 127.0.0.1 eureka-server01 eureka-server02
      defaultZone: http://admin:admin@eureka-server01:8761/eureka/,http://admin:admin@eureka-server02:8762/eureka/